/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivadoRouteImport } from './routes/_privado'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivadoCadastrosRouteImport } from './routes/_privado.cadastros'
import { Route as PrivadoCartoesRouteImport } from './routes/_privado.cartoes'
import { Route as PrivadoContasRouteImport } from './routes/_privado.contas'
import { Route as PrivadoDashboardRouteImport } from './routes/_privado.dashboard'
import { Route as PrivadoPagarRouteImport } from './routes/_privado.pagar'
import { Route as PrivadoPerfilRouteImport } from './routes/_privado.perfil'
import { Route as PrivadoPessoasRouteImport } from './routes/_privado.pessoas'
import { Route as PrivadoReceberRouteImport } from './routes/_privado.receber'
import { Route as PrivadoTransacoesRouteImport } from './routes/_privado.transacoes'
import { Route as PrivadoFaturasIndexRouteImport } from './routes/_privado.faturas.index'
import { Route as PrivadoFaturasIdRouteImport } from './routes/_privado.faturas.$id'
import { Route as PrivadoFaturasNovaRouteImport } from './routes/_privado.faturas.nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivadoRoute = PrivadoRouteImport.update({
  id: '/_privado',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivadoCadastrosRoute = PrivadoCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => PrivadoRoute,
} as any)
const PrivadoCartoesRoute = PrivadoCartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => PrivadoRoute,
} as any)
const PrivadoContasRoute = PrivadoContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => PrivadoRoute,
} as any)
const PrivadoDashboardRoute = PrivadoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivadoRoute,
} as any)
const PrivadoPagarRoute = PrivadoPagarRouteImport.update({
  id: '/pagar',
  path: '/pagar',
  getParentRoute: () => PrivadoRoute,
} as any)
const PrivadoPerfilRoute = PrivadoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PrivadoRoute,
} as any)
const PrivadoPessoasRoute = PrivadoPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => PrivadoRoute,
} as any)
const PrivadoReceberRoute = PrivadoReceberRouteImport.update({
  id: '/receber',
  path: '/receber',
  getParentRoute: () => PrivadoRoute,
} as any)
const PrivadoTransacoesRoute = PrivadoTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => PrivadoRoute,
} as any)
const PrivadoFaturasIndexRoute = PrivadoFaturasIndexRouteImport.update({
  id: '/faturas/',
  path: '/faturas/',
  getParentRoute: () => PrivadoRoute,
} as any)
const PrivadoFaturasIdRoute = PrivadoFaturasIdRouteImport.update({
  id: '/faturas/$id',
  path: '/faturas/$id',
  getParentRoute: () => PrivadoRoute,
} as any)
const PrivadoFaturasNovaRoute = PrivadoFaturasNovaRouteImport.update({
  id: '/faturas/nova',
  path: '/faturas/nova',
  getParentRoute: () => PrivadoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/cadastros': typeof PrivadoCadastrosRoute
  '/cartoes': typeof PrivadoCartoesRoute
  '/contas': typeof PrivadoContasRoute
  '/dashboard': typeof PrivadoDashboardRoute
  '/pagar': typeof PrivadoPagarRoute
  '/perfil': typeof PrivadoPerfilRoute
  '/pessoas': typeof PrivadoPessoasRoute
  '/receber': typeof PrivadoReceberRoute
  '/transacoes': typeof PrivadoTransacoesRoute
  '/faturas/$id': typeof PrivadoFaturasIdRoute
  '/faturas/nova': typeof PrivadoFaturasNovaRoute
  '/faturas/': typeof PrivadoFaturasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/cadastros': typeof PrivadoCadastrosRoute
  '/cartoes': typeof PrivadoCartoesRoute
  '/contas': typeof PrivadoContasRoute
  '/dashboard': typeof PrivadoDashboardRoute
  '/pagar': typeof PrivadoPagarRoute
  '/perfil': typeof PrivadoPerfilRoute
  '/pessoas': typeof PrivadoPessoasRoute
  '/receber': typeof PrivadoReceberRoute
  '/transacoes': typeof PrivadoTransacoesRoute
  '/faturas/$id': typeof PrivadoFaturasIdRoute
  '/faturas/nova': typeof PrivadoFaturasNovaRoute
  '/faturas': typeof PrivadoFaturasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_privado': typeof PrivadoRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_privado/cadastros': typeof PrivadoCadastrosRoute
  '/_privado/cartoes': typeof PrivadoCartoesRoute
  '/_privado/contas': typeof PrivadoContasRoute
  '/_privado/dashboard': typeof PrivadoDashboardRoute
  '/_privado/pagar': typeof PrivadoPagarRoute
  '/_privado/perfil': typeof PrivadoPerfilRoute
  '/_privado/pessoas': typeof PrivadoPessoasRoute
  '/_privado/receber': typeof PrivadoReceberRoute
  '/_privado/transacoes': typeof PrivadoTransacoesRoute
  '/_privado/faturas/$id': typeof PrivadoFaturasIdRoute
  '/_privado/faturas/nova': typeof PrivadoFaturasNovaRoute
  '/_privado/faturas/': typeof PrivadoFaturasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/cadastros'
    | '/cartoes'
    | '/contas'
    | '/dashboard'
    | '/pagar'
    | '/perfil'
    | '/pessoas'
    | '/receber'
    | '/transacoes'
    | '/faturas/$id'
    | '/faturas/nova'
    | '/faturas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/cadastros'
    | '/cartoes'
    | '/contas'
    | '/dashboard'
    | '/pagar'
    | '/perfil'
    | '/pessoas'
    | '/receber'
    | '/transacoes'
    | '/faturas/$id'
    | '/faturas/nova'
    | '/faturas'
  id:
    | '__root__'
    | '/'
    | '/_privado'
    | '/cadastro'
    | '/login'
    | '/_privado/cadastros'
    | '/_privado/cartoes'
    | '/_privado/contas'
    | '/_privado/dashboard'
    | '/_privado/pagar'
    | '/_privado/perfil'
    | '/_privado/pessoas'
    | '/_privado/receber'
    | '/_privado/transacoes'
    | '/_privado/faturas/$id'
    | '/_privado/faturas/nova'
    | '/_privado/faturas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivadoRoute: typeof PrivadoRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_privado': {
      id: '/_privado'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_privado/cadastros': {
      id: '/_privado/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof PrivadoCadastrosRouteImport
      parentRoute: typeof PrivadoRoute
    }
    '/_privado/cartoes': {
      id: '/_privado/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof PrivadoCartoesRouteImport
      parentRoute: typeof PrivadoRoute
    }
    '/_privado/contas': {
      id: '/_privado/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof PrivadoContasRouteImport
      parentRoute: typeof PrivadoRoute
    }
    '/_privado/dashboard': {
      id: '/_privado/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivadoDashboardRouteImport
      parentRoute: typeof PrivadoRoute
    }
    '/_privado/pagar': {
      id: '/_privado/pagar'
      path: '/pagar'
      fullPath: '/pagar'
      preLoaderRoute: typeof PrivadoPagarRouteImport
      parentRoute: typeof PrivadoRoute
    }
    '/_privado/perfil': {
      id: '/_privado/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PrivadoPerfilRouteImport
      parentRoute: typeof PrivadoRoute
    }
    '/_privado/pessoas': {
      id: '/_privado/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof PrivadoPessoasRouteImport
      parentRoute: typeof PrivadoRoute
    }
    '/_privado/receber': {
      id: '/_privado/receber'
      path: '/receber'
      fullPath: '/receber'
      preLoaderRoute: typeof PrivadoReceberRouteImport
      parentRoute: typeof PrivadoRoute
    }
    '/_privado/transacoes': {
      id: '/_privado/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof PrivadoTransacoesRouteImport
      parentRoute: typeof PrivadoRoute
    }
    '/_privado/faturas/': {
      id: '/_privado/faturas/'
      path: '/faturas'
      fullPath: '/faturas/'
      preLoaderRoute: typeof PrivadoFaturasIndexRouteImport
      parentRoute: typeof PrivadoRoute
    }
    '/_privado/faturas/$id': {
      id: '/_privado/faturas/$id'
      path: '/faturas/$id'
      fullPath: '/faturas/$id'
      preLoaderRoute: typeof PrivadoFaturasIdRouteImport
      parentRoute: typeof PrivadoRoute
    }
    '/_privado/faturas/nova': {
      id: '/_privado/faturas/nova'
      path: '/faturas/nova'
      fullPath: '/faturas/nova'
      preLoaderRoute: typeof PrivadoFaturasNovaRouteImport
      parentRoute: typeof PrivadoRoute
    }
  }
}

interface PrivadoRouteChildren {
  PrivadoCadastrosRoute: typeof PrivadoCadastrosRoute
  PrivadoCartoesRoute: typeof PrivadoCartoesRoute
  PrivadoContasRoute: typeof PrivadoContasRoute
  PrivadoDashboardRoute: typeof PrivadoDashboardRoute
  PrivadoPagarRoute: typeof PrivadoPagarRoute
  PrivadoPerfilRoute: typeof PrivadoPerfilRoute
  PrivadoPessoasRoute: typeof PrivadoPessoasRoute
  PrivadoReceberRoute: typeof PrivadoReceberRoute
  PrivadoTransacoesRoute: typeof PrivadoTransacoesRoute
  PrivadoFaturasIdRoute: typeof PrivadoFaturasIdRoute
  PrivadoFaturasNovaRoute: typeof PrivadoFaturasNovaRoute
  PrivadoFaturasIndexRoute: typeof PrivadoFaturasIndexRoute
}

const PrivadoRouteChildren: PrivadoRouteChildren = {
  PrivadoCadastrosRoute: PrivadoCadastrosRoute,
  PrivadoCartoesRoute: PrivadoCartoesRoute,
  PrivadoContasRoute: PrivadoContasRoute,
  PrivadoDashboardRoute: PrivadoDashboardRoute,
  PrivadoPagarRoute: PrivadoPagarRoute,
  PrivadoPerfilRoute: PrivadoPerfilRoute,
  PrivadoPessoasRoute: PrivadoPessoasRoute,
  PrivadoReceberRoute: PrivadoReceberRoute,
  PrivadoTransacoesRoute: PrivadoTransacoesRoute,
  PrivadoFaturasIdRoute: PrivadoFaturasIdRoute,
  PrivadoFaturasNovaRoute: PrivadoFaturasNovaRoute,
  PrivadoFaturasIndexRoute: PrivadoFaturasIndexRoute,
}

const PrivadoRouteWithChildren =
  PrivadoRoute._addFileChildren(PrivadoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivadoRoute: PrivadoRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
